CREATE TABLE IF NOT EXISTS ingredients (
    id   bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS recipes(
    id   bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);

CREATE TABLE IF NOT EXISTS recipes_ingredients (
    recipe_id bigint REFERENCES recipes (id) ON DELETE CASCADE,
    ingredient_id bigint REFERENCES ingredients (id),
    quantity int,
    measure_unit TEXT,
    PRIMARY KEY (recipe_id, ingredient_id)
)